# Generated by Django 5.0.6 on 2024-09-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedItem',
        ),
    ]
