# Generated by Django 5.0.6 on 2024-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_notsubmitteditem_submitteditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notsubmitteditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submitteditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
