# Generated by Django 5.1 on 2024-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_alter_notsubmitteditem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsubmitteditem',
            name='tableNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submitteditem',
            name='tableNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
