# Generated by Django 5.1 on 2024-09-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_notsubmitteditem_tablenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tableNumber', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
