# Generated by Django 5.0.6 on 2024-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
