# Generated by Django 5.0.6 on 2024-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteditem',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
